import Head from "next/head";
import Image from "next/image";
import { useQuery } from "urql";
import { PRODUCT_QUERY } from "../lib/query";
import Product from "../components/Product";
import { Gallery } from "../styles/Gallery";
import MainBanner from "../components/Banner";

export default function Home() {
  //Fetching data from strapi
  const [results] = useQuery({ query: PRODUCT_QUERY });
  const { data, fetching, error } = results;
  //checking data incoming
  if (fetching) return <p>Loading..</p>;
  if (error) return <p>Error {error.message}</p>;
  const products = data.products.data;
  return (
    <div>
      <Head>
        <title>Changed</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <MainBanner />
        <h1 align="center">Our Products</h1>
        <Gallery>
          {products.map((product) => (
            <Product key={product.attributes.Slug} product={product} />
          ))}
        </Gallery>
      </main>
    </div>
  );
}
